channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - snakemake=3.13.3
  - fastqc=0.11.5
  - samtools=1.4
  - trimmomatic=0.36
  - bwa=0.7.15
  - picard=2.9.2
  - gatk=3.5
  - varscan=2.4.2
  - qualimap=2.2
  - sra-tools=2.8.1
